version: 0.2

phases:
  install:
    commands:
      - sudo apt update 
      - sudo apt install git
      - sudo apt install python3-pip -y
      - sudo pip install boto3
      - wget https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_arm64.zip
      - unzip terraform_1.4.6_linux_arm64.zip
      - sudo mv terraform /bin
      - rm terraform_1.4.6_linux_arm64.zip
      - apt-get update
      - apt-cache search source
      - echo "Prepare terraform file"
      - git clone https://github.com/davidortizac/fortigate-terraform-deploy.git 
      - cd fortigate-terraform-deploy/aws/7.2/single
      - terraform init
  pre_build:
    commands:
     - cd fortigate-terraform-deploy/aws/7.2/single
     - terraform plan
  build:
    commands:
     - cd fortigate-terraform-deploy/aws/7.2/single
     - terraform apply -auto-approve
     - echo "Apply stage finished"
  post_build:
    commands:
      - echo "Nothing to do in the post_build for now"
      